# Generated by Django 3.1.2 on 2020-12-27 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0003_auto_20201227_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='iso',
            old_name='name',
            new_name='iso',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='name',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='name',
            new_name='states',
        ),
    ]
