# Generated by Django 3.1.2 on 2020-12-27 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0006_auto_20201227_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iso',
            old_name='iso',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='region',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='states',
            new_name='name',
        ),
    ]
